version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  development-mocklogin:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: development-mocklogin
    ports:
      - "9999:80"
  development-login:
    image: lblod/mock-login-service
    container_name: development-login
    ports:
      - "9998:80"
networks:
  proxy:
    external:
      name: letsencrypt_default
  backend:
    external: true
