version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  development-mocklogin:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: development-mocklogin
    ports:
      - "9999:80"
    networks:
      - proxy
      - default
      - backend
    external_links:
      - development-database:database

networks:
  proxy:
    external:
      name: letsencrypt_default
  backend:
    external: true
