version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  mocklogin:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mocklogin
    networks:
      - proxy
      - default
      - backend
    external_links:
      - database:database
  login:
    image: lblod/mock-login-service
    container_name: login
    networks:
      - proxy
      - default
      - backend
    external_links:
      - database:database

networks:
  proxy:
    external:
      name: letsencrypt_default
  backend:
    external: true
